In [1]:
import pandas as pd

# df=pd.DataFrame({'x':[1,2,3,4,5,6,7,8,9]})
# 逻辑表达式测试
df = pd.DataFrame({'a': [True, True, True, False, False, False, False],
                   'b': [True, True, False, False, True, False, True],
                   'c': [True, False, False, False, False, True, True]
                   })

df['a & b & c'] = df['a'] & df['b'] & df['c']
print(df)

       a      b      c  a & b & c
0   True   True   True       True
1   True   True  False      False
2   True  False  False      False
3  False  False  False      False
4  False   True  False      False
5  False  False   True      False
6  False   True   True      False


In [2]:
import pandas as pd

# df=pd.DataFrame({'x':[1,2,3,4,5,6,7,8,9]})
# 逻辑表达式测试
df = pd.DataFrame({'a': [True, True, True, False, False, False, False],
                   'b': [True, True, False, False, True, False, True],
                   'c': [True, False, False, False, False, True, True]
                   })

df['x1'] = df['a'] & df['b']
df['x2'] = df['x1'] & df['c']
print(df)

       a      b      c     x1     x2
0   True   True   True   True   True
1   True   True  False   True  False
2   True  False  False  False  False
3  False  False  False  False  False
4  False   True  False  False  False
5  False  False   True  False  False
6  False   True   True  False  False


In [3]:
import pandas as pd

# df=pd.DataFrame({'x':[1,2,3,4,5,6,7,8,9]})
# 逻辑表达式测试
df = pd.DataFrame({'a': [True, True, True, False, False, False, False],
                   'b': [True, True, False, False, True, False, True],
                   'c': [True, False, False, False, False, True, True]
                   })
df1 = df.query('a & b & c')
print(df1)

      a     b     c
0  True  True  True


In [4]:
import pandas as pd

# df=pd.DataFrame({'x':[1,2,3,4,5,6,7,8,9]})
# 逻辑表达式测试
df = pd.DataFrame({'a': [True, True, True, False, False, False, False],
                   'b': [True, True, False, False, True, False, True],
                   'c': [True, False, False, False, False, True, True]
                   })
#df['a & b & c'] = df.query('a & b & c')
df1 = df.eval('a & b & c')
print(df1)

0     True
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool


In [5]:
from quant1x.formula import CONST
import pandas as pd

t1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
df = pd.DataFrame({'x': t1})
x = df['x'].values
print(CONST(x))

[9 9 9 9 9 9 9 9 9]


In [6]:
t1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
t2 = [0, 0, 0, 0, 0, 0, 0, 0, 0]
t2[0:2] = t1[0:2]
print(t2)

[1, 2, 0, 0, 0, 0, 0, 0, 0]


In [7]:
from quant1x.formula import CONST
import pandas as pd

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9]})
x = df['x'].values
print(CONST(x))

[9 9 9 9 9 9 9 9 9]


In [8]:
import pandas as pd

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
x = df['x'].rolling(5).mean().values
print(x)

[nan nan nan nan  3.  4.  5.  6.  7.  8.]


In [9]:
import pandas as pd

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
x = df['x'].rolling(5).std().values
print(x)

[       nan        nan        nan        nan 1.58113883 1.58113883
 1.58113883 1.58113883 1.58113883 1.58113883]


In [10]:
import pandas as pd

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
x = df['x'].rolling(5).max()
print(x)

0     NaN
1     NaN
2     NaN
3     NaN
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
Name: x, dtype: float64


In [11]:
import numpy as np

x1 = np.nan
x2 = np.where(x1, 1, 2)
print(x2)

1


In [12]:
import pandas as pd
from quant1x.base.formula import *

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]})
print(df)
print('------------------------------------------------------------')
N = 5
print("固定的参数: N = %d" % (N))
s1 = df['x'].rolling(5).mean().values
print("序列化结果:", s1)
print('------------------------------------------------------------')
s2 = np.array([1, 2, 3, 4, 3, 3, 2, 1, np.nan, np.nan, np.nan, np.nan])
print("序列化参数: N =", s2)
v2 = MA(df['x'], s2)
print("序列化结果:", v2)

     x
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
------------------------------------------------------------
固定的参数: N = 5
序列化结果: [nan nan nan nan  3.  4.  5.  6.  7.  8.  9. 10.]
------------------------------------------------------------
序列化参数: N = [ 1.  2.  3.  4.  3.  3.  2.  1. nan nan nan nan]
序列化结果: [1.  1.5 2.  2.5 4.  5.  6.5 8.  nan nan nan nan]


In [13]:
from quant1x.base.formula import *

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]})
print(df)
print('------------------------------------------------------------')
N = 1
print("固定的参数: N = %d" % (N))
v2 = DIFF(df['x'], N)
print("序列化结果:", v2)

     x
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
------------------------------------------------------------
固定的参数: N = 1
序列化结果: [nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [14]:
from quant1x.base.formula import *

df = pd.DataFrame({'x': [0, 0.5, np.nan, np.nan]})
print(df)
print('------------------------------------------------------------')
N = 2
print("固定的参数: N = %d" % (N))
v2 = HHV(df['x'], N)
print("序列化结果:", v2)

     x
0  0.0
1  0.5
2  NaN
3  NaN
------------------------------------------------------------
固定的参数: N = 2
序列化结果: [nan 0.5 nan nan]


In [15]:
from quant1x.base.formula import *

df = pd.DataFrame({'x': [0, 0.5, np.nan, np.nan]})
print(df)
print('------------------------------------------------------------')
N = 2
print("固定的参数: N = %d" % (N))
v2 = LLV(df['x'], N)
print("序列化结果:", v2)

     x
0  0.0
1  0.5
2  NaN
3  NaN
------------------------------------------------------------
固定的参数: N = 2
序列化结果: [nan  0. nan nan]


In [16]:
print(np.max([1.4, np.nan]))
print(np.maximum([1.4], [np.nan]))
print(np.minimum([1.4], [np.nan]))

nan
[nan]
[nan]


In [17]:
from quant1x.base.formula import *

f1 = [1.1, 2.2, 1.3, 1.4]
r1 = STD(f1, 4)
print(r1)
f2 = [70, 80, 75, 83, 86]
r2 = STD(f2, 5)
print(r2)

[       nan        nan        nan 0.41833001]
[       nan        nan        nan        nan 5.70613705]


In [18]:
# 测试Std
#pandas计算方法
#axis = 0表示跨行，axis=1表示跨列

import pandas as pd

data_dic = {'c1': [1, 2, 3],
            'c2': [1, 3, 5]}
df = pd.DataFrame(data_dic)
#c1列的meam
mean = df['c1'].mean()
#or
mean = df.iloc[:, 0].mean()
#c1列的var
var = df['c1'].var()  #计算的无偏样本方差
var = df['c1'].values.var()  #计算的是有偏的总体方差
#c1列的std
std = df['c1'].std()
std = df['c1'].values.std()


In [19]:
# 测试WMA
from quant1x.base.formula import *

f1 = [1, 2, 3, 4]
r1 = pd.Series(f1)[::-1]
print(r1)
r2 = r1.cumsum()
print(r2)
r3 = r2.sum()
print(r3)
print(WMA(f1, 4))

3    4
2    3
1    2
0    1
dtype: int64
3     4
2     7
1     9
0    10
dtype: int64
30
[nan nan nan  3.]


In [20]:
# 测试CONST
from quant1x.base.formula import *

f1 = [1, 2, 3, 4]
r1 = CONST(f1)
print(r1)


[4 4 4 4]


In [21]:
# 测试SMA
from quant1x.base.formula import *

f1 = [1, 2, 3, 4]
r1 = SMA(f1, 4)
print(r1)


[1.       1.25     1.6875   2.265625]


In [22]:
# 测试BARSSINCEN
from quant1x.base.formula import *

f1 = [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
df = pd.Series(f1)
print(df)
c1 = df > 3
r1 = BARSSINCEN(c1, 4)
print(r1)

0     1
1     2
2     3
3     4
4     1
5     2
6     3
7     4
8     1
9     2
10    3
11    4
dtype: int64
[0 0 0 0 1 2 3 0 1 2 3 0]


In [23]:
# 测试EMA
from quant1x.base.formula import *

f1 = [1, 2, 3, 4]
r1 = EMA(f1, 4)
print(r1)
f2 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
r2 = EMA(f2, 7)
print(r2)

[1.    1.4   2.04  2.824]
[1.         1.25       1.6875     2.265625   2.94921875 3.71191406
 4.53393555 5.40045166 6.30033875]


In [24]:
# 测试DMA
from quant1x.base.formula import *

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]})
print(df)
print('------------------------------------------------------------')
print('DMA(S, A)')
N = 5
print("固定的参数: N = %d" % (N))
S = df['x']
s1 = DMA(S, 1 / N)
print("序列化结果:", s1)
print('------------------------------------------------------------')
s2 = np.array([1, 2, 3, 4, 3, 3, 2, 1, np.nan, np.nan, np.nan, np.nan])
print(s2)
A = np.array(s2)
A[np.isnan(A)] = 1.0
print(A)
print("序列化参数: N =", A)
v2 = DMA(S, 1 / s2)
print("序列化结果:", v2)

     x
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
------------------------------------------------------------
DMA(S, A)
固定的参数: N = 5
序列化结果: [1.         1.2        1.56       2.048      2.6384     3.31072
 4.048576   4.8388608  5.67108864 6.53687091 7.42949673 8.34359738]
------------------------------------------------------------
[ 1.  2.  3.  4.  3.  3.  2.  1. nan nan nan nan]
[1. 2. 3. 4. 3. 3. 2. 1. 1. 1. 1. 1.]
序列化参数: N = [1. 2. 3. 4. 3. 3. 2. 1. 1. 1. 1. 1.]
序列化结果: [ 1.          1.5         2.          2.5         3.33333333  4.22222222
  5.61111111  8.          9.         10.         11.         12.        ]


In [25]:
# LAST
from quant1x.base.formula import *

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]})
print(df)
print('------------------------------------------------------------')
print('LAST(X, A, B)')
N = 5
print("固定的参数: N = %d" % (N))
S = df['x']
s1 = LAST(S > 10, 10, 5)
print("序列化结果:", s1)
print('------------------------------------------------------------')
s2 = np.array([1, 2, 3, 4, 3, 3, 2, 1, np.nan, np.nan, np.nan, np.nan])
print(s2)
A = np.array(s2)
A[np.isnan(A)] = 1.0
print(A)
print("序列化参数: N =", A)
v2 = DMA(S, 1 / s2)
print("序列化结果:", v2)

     x
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
------------------------------------------------------------
LAST(X, A, B)
固定的参数: N = 5
序列化结果: [ True  True  True  True  True  True  True  True  True  True False False]
------------------------------------------------------------
[ 1.  2.  3.  4.  3.  3.  2.  1. nan nan nan nan]
[1. 2. 3. 4. 3. 3. 2. 1. 1. 1. 1. 1.]
序列化参数: N = [1. 2. 3. 4. 3. 3. 2. 1. 1. 1. 1. 1.]
序列化结果: [ 1.          1.5         2.          2.5         3.33333333  4.22222222
  5.61111111  8.          9.         10.         11.         12.        ]


In [26]:
from numpy import poly1d
# 线性回归
import numpy as np
import numpy.core.numeric as NX

print('------------------------------------------------------------')
x = [0.0, 0.1, 0.2, 0.3, 0.5, 0.8, 1.0]
y = [1.0, 0.41, 0.50, 0.61, 0.91, 2.02, 2.46]
A = np.polyfit(x, y, 2)
print(A)
#A = A[::-1]
print(A)
print('------------------------------------------------------------')
z = np.polyval(A, x)
print(z)
print('------------------------------------------------------------')

------------------------------------------------------------
[ 3.13156135 -1.24003678  0.73557673]
[ 3.13156135 -1.24003678  0.73557673]
------------------------------------------------------------
[0.73557673 0.64288867 0.61283183 0.64540622 0.89844868 1.74774657
 2.6271013 ]
------------------------------------------------------------


In [27]:
# SLOPE
from quant1x.base.formula import *

df = pd.DataFrame({'x': [1.0, 0.41, 0.50, 0.61, 0.91, 2.02, 2.46]})
print(df)
print('------------------------------------------------------------')
print('SLOPE(X, N)')
N = 5
print(range(N))
print("固定的参数: N = %d" % (N))
S = df['x']
s1 = SLOPE(S, N)
print("序列化结果:", s1)
print('------------------------------------------------------------')
s2 = np.array([1, 2, 3, 4, 3, 3, 2, 1, np.nan, np.nan, np.nan, np.nan])
print(s2)
print("序列化参数: N =", s2)
v2 = SLOPE(S, s2)
print("序列化结果:", v2)

      x
0  1.00
1  0.41
2  0.50
3  0.61
4  0.91
5  2.02
6  2.46
------------------------------------------------------------
SLOPE(X, N)
range(0, 5)
固定的参数: N = 5
序列化结果: [  nan   nan   nan   nan 0.002 0.363 0.533]
------------------------------------------------------------
[ 1.  2.  3.  4.  3.  3.  2.  1. nan nan nan nan]
序列化参数: N = [ 1.  2.  3.  4.  3.  3.  2.  1. nan nan nan nan]


ValueError: window must be an integer 0 or greater

In [ ]:
# AVEDEV
from quant1x.base.formula import *

df = pd.DataFrame({'x': [1.0, 0.41, 0.50, 0.61, 0.91, 2.02, 2.46]})
print(df)
print('------------------------------------------------------------')
print('AVEDEV(X, N)')
N = 5
print(range(N))
print("固定的参数: N = %d" % (N))
S = df['x']
s1 = AVEDEV(S, N)
print("序列化结果:", s1)
print('------------------------------------------------------------')
s2 = np.array([1, 2, 3, 4, 3, 3, 2, 1, np.nan, np.nan, np.nan, np.nan])
print(s2)
print("序列化参数: N =", s2)
v2 = AVEDEV(S, s2)
print("序列化结果:", v2)

In [ ]:
# FORCAST
from quant1x.base.formula import *

df = pd.DataFrame({'x': [1.0, 0.41, 0.50, 0.61, 0.91, 2.02, 2.46]})
print(df)
print('------------------------------------------------------------')
print('FORCAST(X, N)')
N = 5
print(range(N))
print("固定的参数: N = %d" % (N))
S = df['x']
s1 = FORCAST(S, N)
print("序列化结果:", s1)
print('------------------------------------------------------------')
s2 = np.array([1, 2, 3, 4, 3, 3, 2, 1, np.nan, np.nan, np.nan, np.nan])
print(s2)
print("序列化参数: N =", s2)
v2 = FORCAST(S, s2)
print("序列化结果:", v2)

In [ ]:
from quant1x.base.formula import *
d = np.array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])
#d[1:3]=5
print(d)
r = FILTER(d,5)
print(r)

In [3]:
# BARSLAST
from quant1x.base.formula import *
d = np.array([1, 2, 3, 4, 5, 6, 0, 8, 9, 10, 11, 12])
#d[1:3]=5
print(d)
r = BARSLAST(d > 1)
print(r)

[ 1  2  3  4  5  6  0  8  9 10 11 12]
[1 0 0 0 0 0 1 0 0 0 0 0]


In [2]:
import numpy as np
d = np.array([1, 2, 3, 4, 5, 6, 0, 8, 9, 10, 11, 12])
S = d > 100
print(S)
M0 = np.where(S, 1, 0)
print(M0)
M = np.concatenate(([0], M0))
print(M)
for i in range(1, len(M)):  M[i] = 0 if M[i] else M[i - 1] + 1
print(M[1:])

[False False False False False False False False False False False False]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
